#!/bin/bash

# TODO: source atrato-env.sh for environment variables like HADOOP_PREFIX for installed mode
# if not exists, assume development mode

build_dir="$( dirname "$0" )/../../../target"
atrato_server_jar=$(echo $build_dir/atrato-server.jar)
java_exec=$JAVA_HOME/bin/java

HADOOP_PREFIX=${HADOOP_PREFIX:-$HADOOP_HOME}

if [ -d "$HADOOP_PREFIX" ]; then
  hadoop_classpath=$($HADOOP_PREFIX/bin/hadoop classpath)
else
  hadoop_classpath=$BUILD_DIR/hadoop-lib/*
fi

if [ ! -z "$ATRATO_SERVER_LISTEN_ADDRESS" ]; then
  ATRATO_SERVER_DEFAULT_OPTS="$ATRATO_SERVER_DEFAULT_OPTS -listenAddress $ATRATO_SERVER_LISTEN_ADDRESS"
fi

if [ ! -z "$ATRATO_SERVER_CONFIG_LOCATION" ]; then
  ATRATO_SERVER_DEFAULT_OPTS="$ATRATO_SERVER_DEFAULT_OPTS -configLocation $ATRATO_SERVER_CONFIG_LOCATION"
fi

$java_exec -cp $atrato_server_jar:$build_dir/lib/*:$hadoop_classpath $ATRATO_SERVER_JVM_OPTS io.atrato.server.AtratoServer $ATRATO_SERVER_DEFAULT_OPTS "$@"
